/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SmartSearch {
        /**
          * @default 'auto'
         */
        "theme": 'light' | 'dark' | 'auto';
    }
}
declare global {
    interface HTMLSmartSearchElement extends Components.SmartSearch, HTMLStencilElement {
    }
    var HTMLSmartSearchElement: {
        prototype: HTMLSmartSearchElement;
        new (): HTMLSmartSearchElement;
    };
    interface HTMLElementTagNameMap {
        "smart-search": HTMLSmartSearchElement;
    }
}
declare namespace LocalJSX {
    interface SmartSearch {
        /**
          * @default 'auto'
         */
        "theme"?: 'light' | 'dark' | 'auto';
    }
    interface IntrinsicElements {
        "smart-search": SmartSearch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "smart-search": LocalJSX.SmartSearch & JSXBase.HTMLAttributes<HTMLSmartSearchElement>;
        }
    }
}
